name: Upload artifact

on:
   push:
     branches: [tutorial]
   pull_request:
     branches: [master]

jobs:
  artifact_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p artifacts

      - run: echo 'PMI best group' > artifacts/the_truth.txt

      - uses: actions/upload-artifact@v2
        with:
          name: useful_info
          path: artifacts

  artifact_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: useful_info
          
      - run: cat useful_info
